In [1]:
import pandas as pd
import numpy as np

In [101]:
def get_courses_period(file, semester_even):
    df = pd.read_csv(file)
    #print(df)
    if semester_even is True:
        df = df.drop(df[(df.Semestre % 2) != 0].index)
    else:
        df = df.drop(df[(df.Semestre % 2) == 0].index)
    return df

In [102]:
def dict_courses_period(df):
    courses_period = {}
    for index, row in df.iterrows():
        #print(row['Clave'],row['P1'], row['P2'], row['P3'])
        periods = [i for i,p in enumerate([row['P1'], row['P2'], row['P3']],1) if p != '-']
        #print(periods)
        courses_period[row['Clave']] = periods
    print(courses_period)
    #return courses_period

In [103]:
#f = pd.read_csv('D:\\Principal\\Escuela\\Actual\\TEC\\semestre8\\tc3002b\\reto\\solucion\\group-problem-resolution\\Stage2\\csvs\\UDF.csv')
#s = 2
#f = f.fillna('-')
#f = f.drop(f[(f.Semestre % 2) == 0].index)
#f
df = get_courses_period('D:\\Principal\\Escuela\\Actual\\TEC\\semestre8\\tc3002b\\reto\\solucion\\group-problem-resolution\\Stage2\\csvs\\UDF.csv', True)
df

,Clave,Nombre,UDC,P1,P2,P3,Semestre,Horas
3,TC1030,Programación orientada a objetos,1,NaN,NaN,X,2,20
8,TC1002B,Herramientas Tecnológicas para Ciencias Sociales,3,NaN,X,NaN,4,60
9,TC1003B,Modelación de la ingeniería con matemática com...,3,X,NaN,NaN,2,60
11,TC2037,Implementación de métodos computacionales,3,X,X,X,4,60
13,TC2005B,Construcción de software y toma de decisiones,8,X,X,NaN,4,160
14,TC2006B,Interconexión de dispositivos,4,NaN,NaN,X,4,80
17,TC3001B,Desarrollo de software,18,X,X,X,6,360
18,TC3002B,Desarrollo de aplicaciones avanzadas de cienci...,6,NaN,X,NaN,8,120
19,TC3003B,Implementación de redes de área amplia y servi...,6,NaN,NaN,X,8,120
20,TC3004B,Planeación de sistemas de software,6,X,NaN,NaN,8,120
21,TC3005B,Desarrollo e implantación de sistemas de software,12,NaN,X,X,8,240
25,TI3005B,Trasformación digital de organizaciones de la ...,6,X,NaN,NaN,8,120

In [104]:
dict_courses_period(df)

{'TC1030': [1, 2, 3], 'TC1002B': [1, 2, 3], 'TC1003B': [1, 2, 3], 'TC2037': [1, 2, 3], 'TC2005B': [1, 2, 3], 'TC2006B': [1, 2, 3], 'TC3001B': [1, 2, 3], 'TC3002B': [1, 2, 3], 'TC3003B': [1, 2, 3], 'TC3004B': [1, 2, 3], 'TC3005B': [1, 2, 3], 'TI3005B': [1, 2, 3]}